"""Container healthcheck for the backend.

The backend refuses connections without a client certificate, so the probe has
to present one. It uses the dedicated ``probe`` pair generated by
``scripts/generate-dev-certs.py``: the backend therefore only ever holds a
private key of its own, never the agent or nginx one.

``/healthz`` is probed rather than ``/readyz`` on purpose. The backend is
designed to keep accepting and spooling events while PostgreSQL is down, so a
database outage must not make the container look dead and get it killed; the
readiness of the database is reported by ``/readyz`` for whoever wants it.
"""

from __future__ import annotations

import http.client
import os
import ssl
import sys
from urllib.parse import urlsplit

URL = os.environ.get("HEALTHCHECK_URL", "https://127.0.0.1:8443/healthz")
CA_CERT = os.environ.get("HEALTHCHECK_CA", "/certs/ca.crt")
CLIENT_CERT = os.environ.get("HEALTHCHECK_CERT", "/certs/probe.crt")
CLIENT_KEY = os.environ.get("HEALTHCHECK_KEY", "/certs/probe.key")
TIMEOUT = float(os.environ.get("HEALTHCHECK_TIMEOUT", "5"))


def main() -> int:
    parts = urlsplit(URL)
    if parts.scheme != "https" or not parts.hostname:
        print(f"HEALTHCHECK_URL must be an https URL, got {URL!r}", file=sys.stderr)
        return 2

    for label, path in (("CA", CA_CERT), ("certificate", CLIENT_CERT), ("key", CLIENT_KEY)):
        if not os.path.isfile(path):
            print(f"healthcheck {label} not found: {path}", file=sys.stderr)
            return 2

    context = ssl.create_default_context(cafile=CA_CERT)
    context.minimum_version = ssl.TLSVersion.TLSv1_3
    context.load_cert_chain(certfile=CLIENT_CERT, keyfile=CLIENT_KEY)

    target = parts.path or "/"
    if parts.query:
        target = f"{target}?{parts.query}"

    try:
        # HTTPSConnection is not a context manager, unlike HTTPConnection, so it
        # has to be closed explicitly.
        connection = http.client.HTTPSConnection(
            parts.hostname,
            parts.port or 443,
            context=context,
            timeout=TIMEOUT,
        )
        try:
            connection.request("GET", target)
            response = connection.getresponse()
            response.read()
        finally:
            connection.close()
    except Exception as exc:  # noqa: BLE001 - the probe reports, it never raises
        print(f"healthcheck against {URL} failed: {exc}", file=sys.stderr)
        return 1

    if response.status != 200:
        print(f"healthcheck against {URL} answered HTTP {response.status}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
